version: '2.4'

services:

  postgresql:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.10-rc-management-alpine
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"

  auth:
    build:
      context: ./auth
      args:
        - NODE_ENV=development
      target: dev
    ports:
      - "3002:3000"
    volumes:
      - ./auth:/app/
    environment:
      - SERVICE=auth
    env_file:
      - ./auth/.env
    depends_on:
      - postgresql
      - rabbitmq

  products:
    build:
      context: ./products
      args:
        - NODE_ENV=development
      target: dev
    ports:
      - "3001:3000"
    volumes:
      - ./products:/app/
    environment:
      - SERVICE=products
    env_file:
      - ./products/.env
    depends_on:
      - postgresql
      - rabbitmq

volumes:
  data:


